[package]
name = "quiet_panics"
version = "0.1.2"
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
log = "0.4"

[features]
panic_payload_as_str = []
